# Generated by Django 3.0.3 on 2020-03-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20200317_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='categories',
        ),
    ]
