# Generated by Django 3.0.3 on 2020-03-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_category_flex_expense_flex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_flex',
            name='date_payment',
        ),
    ]
