# Generated by Django 3.0.3 on 2020-03-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_remove_expense_flex_date_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_flex',
            name='amount',
        ),
    ]
