# Generated by Django 3.0.3 on 2020-03-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_auto_20200320_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_payment',
            field=models.IntegerField(),
        ),
    ]
